# ---------------------------------------------------------------------------- #
#                                 Configuration                                #
# ---------------------------------------------------------------------------- #
author: "Andrea Spada"
theme: "hugo-chisel"
title: "Liuteria d'Autore"

# ---------------------------------------------------------------------------- #
#                                    Locales                                   #
# ---------------------------------------------------------------------------- #
defaultContentLanguage: "en"
defaultContentLanguageInSubDir: true
enableMissingTranslationPlaceholders: true
hasCJKLanguage: false
removePathAccents: true

# ---------------------------------------------------------------------------- #
#                            Hugo Built-in Features                            #
# ---------------------------------------------------------------------------- #
Hugo Built-in FeaturesdisableKinds:
enableInlineShortcodes: true

# ---------------------------------------------------------------------------- #
#                                    render                                    #
# ---------------------------------------------------------------------------- #
canonifyURLs: false
uglyurls: false
disableAliases: false
disableHugoGeneratorInject: false
disableLiveReload: false
enableEmoji: true
enableGitInfo: false
ignoreCache: true
ignoreFiles: []
metaDataFormat: "yaml"
verbose: true
watch: true
