# -------------------------------- taxonomies -------------------------------- #
language: 'languages'
article: 'articles'
articolo: 'articoli'
artigo: 'artigos'
publication: 'publications'
publicacion: 'publicaciones'
tag: 'tags'
